import { PrismaClient } from '@prisma/client'
import path from 'path'

// Resolve DB path relative to project root
process.env.DATABASE_URL = process.env.DATABASE_URL ?? `file:${path.resolve(__dirname, 'portfolio.db')}`

const prisma = new PrismaClient({
  datasources: { db: { url: process.env.DATABASE_URL } },
})

const holdings = [
  {
    ticker: 'AVGO',
    name: 'Broadcom Inc.',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 0.2462,
    bookValueCAD: 139.45,
    bookValueMkt: 99.954,
    bookValueMktCurrency: 'USD',
    marketPrice: 401.335,
    marketPriceCurrency: 'USD',
    marketValue: 98.754,
    marketValueCurrency: 'USD',
    unrealizedReturn: -1.199,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'AI / Semis',
    conviction: 8,
    horizon: 'LONG',
    targetPct: 7,
    thesis: 'Custom AI ASIC leader. Google TPU, Meta MTIA, Apple custom silicon. VMware integration complete, recurring revenue growing strongly.',
  },
  {
    ticker: 'GDX',
    name: 'VanEck Gold Miners ETF',
    exchange: 'NYSE',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 0.9832,
    bookValueCAD: 152.15,
    bookValueMkt: 108.988,
    bookValueMktCurrency: 'USD',
    marketPrice: 94.57,
    marketPriceCurrency: 'USD',
    marketValue: 92.922,
    marketValueCurrency: 'USD',
    unrealizedReturn: -16.066,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Core',
    theme: 'Commodities',
    conviction: 6,
    horizon: 'MEDIUM',
    targetPct: 7,
    thesis: 'Gold miner leverage play. Operating leverage to gold price with improving free cash flow generation. Inflation and USD-weakness hedge.',
  },
  {
    ticker: 'GOLD',
    name: 'Physically Backed Gold',
    exchange: 'N/A',
    securityType: 'PRECIOUS_METAL',
    quantity: 0.03435,
    bookValueCAD: 250.0,
    bookValueMkt: 250.0,
    bookValueMktCurrency: 'CAD',
    marketPrice: 6416.505,
    marketPriceCurrency: 'CAD',
    marketValue: 220.408,
    marketValueCurrency: 'CAD',
    unrealizedReturn: -29.592,
    unrealizedReturnCurrency: 'CAD',
    bucket: 'Core',
    theme: 'Commodities',
    conviction: 6,
    horizon: 'MEDIUM',
    targetPct: 5,
    thesis: 'Physical gold store of value. Complements GDX with direct commodity exposure. Geopolitical and inflation hedge.',
  },
  {
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 0.1887,
    bookValueCAD: 179.03,
    bookValueMkt: 128.329,
    bookValueMktCurrency: 'USD',
    marketPrice: 671.33,
    marketPriceCurrency: 'USD',
    marketValue: 126.628,
    marketValueCurrency: 'USD',
    unrealizedReturn: -1.701,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'AI / Social',
    conviction: 7,
    horizon: 'MEDIUM',
    targetPct: 8,
    thesis: 'AI-powered ad targeting + Reality Labs optionality. Llama models, WhatsApp monetization, Instagram Reels growth. Strong FCF generation.',
  },
  {
    ticker: 'NDAQ',
    name: 'Nasdaq Inc.',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 0.7546,
    bookValueCAD: 106.34,
    bookValueMkt: 75.181,
    bookValueMktCurrency: 'USD',
    marketPrice: 87.75,
    marketPriceCurrency: 'USD',
    marketValue: 66.216,
    marketValueCurrency: 'USD',
    unrealizedReturn: -8.964,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'Fintech',
    conviction: 7,
    horizon: 'LONG',
    targetPct: 3,
    thesis: 'Financial infrastructure and index licensing. Recurring revenue, market data moat. Adenza acquisition adds software revenue stream.',
  },
  {
    ticker: 'NLR',
    name: 'VanEck Uranium + Nuclear Energy ETF',
    exchange: 'NYSE',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 1.0071,
    bookValueCAD: 211.28,
    bookValueMkt: 149.988,
    bookValueMktCurrency: 'USD',
    marketPrice: 140.72,
    marketPriceCurrency: 'USD',
    marketValue: 141.85,
    marketValueCurrency: 'USD',
    unrealizedReturn: -8.138,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Core',
    theme: 'Nuclear Energy',
    conviction: 8,
    horizon: 'LONG',
    targetPct: 8,
    thesis: 'Power demand from AI data centers requires nuclear baseload. Policy tailwinds, SMR pipeline, uranium supply tightness. Long-duration thesis.',
  },
  {
    ticker: 'NVDA',
    name: 'NVIDIA Corp',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 1.8594,
    bookValueCAD: 470.33,
    bookValueMkt: 335.066,
    bookValueMktCurrency: 'USD',
    marketPrice: 199.83,
    marketPriceCurrency: 'USD',
    marketValue: 371.46,
    marketValueCurrency: 'USD',
    unrealizedReturn: 36.394,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Core',
    theme: 'AI / Semis',
    conviction: 10,
    horizon: 'LONG',
    targetPct: 18,
    thesis: 'AI infrastructure backbone. Data center GPU near-monopoly with Blackwell ramp, CUDA moat, and hyperscaler capex cycle. Highest conviction holding.',
  },
  {
    ticker: 'PLTR',
    name: 'Palantir Technologies Inc (Class A)',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 0.3447,
    bookValueCAD: 69.73,
    bookValueMkt: 49.983,
    bookValueMktCurrency: 'USD',
    marketPrice: 146.78,
    marketPriceCurrency: 'USD',
    marketValue: 50.595,
    marketValueCurrency: 'USD',
    unrealizedReturn: 0.612,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'AI / GovTech',
    conviction: 7,
    horizon: 'LONG',
    targetPct: 4,
    thesis: 'Government and commercial AI platform. AIP product gaining enterprise traction. Expensive but defensible moat in mission-critical data analytics.',
  },
  {
    ticker: 'QQQM',
    name: 'Invesco Nasdaq 100 ETF',
    exchange: 'NASDAQ',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 1.0968,
    bookValueCAD: 372.55,
    bookValueMkt: 265.879,
    bookValueMktCurrency: 'USD',
    marketPrice: 265.75,
    marketPriceCurrency: 'USD',
    marketValue: 291.341,
    marketValueCurrency: 'USD',
    unrealizedReturn: 25.462,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Core',
    theme: 'Tech',
    conviction: 8,
    horizon: 'LONG',
    targetPct: 12,
    thesis: 'Tech index core. Efficient exposure to top 100 Nasdaq companies. Low cost, diversified, tax-efficient TFSA anchor.',
  },
  {
    ticker: 'QTUM',
    name: 'Defiance Quantum ETF',
    exchange: 'NASDAQ',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 1.7842,
    bookValueCAD: 293.203,
    bookValueMkt: 208.19,
    bookValueMktCurrency: 'USD',
    marketPrice: 128.5,
    marketPriceCurrency: 'USD',
    marketValue: 229.27,
    marketValueCurrency: 'USD',
    unrealizedReturn: 21.08,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Speculative',
    theme: 'Quantum Computing',
    conviction: 5,
    horizon: 'LONG',
    targetPct: 2,
    thesis: 'Optionality on quantum computing adoption. Small position as thematic bet. Timeline uncertain but asymmetric upside if practical applications emerge.',
  },
  {
    ticker: 'SMHX',
    name: 'VanEck Fabless Semiconductor ETF',
    exchange: 'NASDAQ',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 1.2732,
    bookValueCAD: 70.7,
    bookValueMkt: 49.985,
    bookValueMktCurrency: 'USD',
    marketPrice: 47.54,
    marketPriceCurrency: 'USD',
    marketValue: 60.528,
    marketValueCurrency: 'USD',
    unrealizedReturn: 10.543,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'Semis',
    conviction: 7,
    horizon: 'MEDIUM',
    targetPct: 5,
    thesis: 'Diversified fabless semi exposure. Captures HBM, memory design, and AI chip ecosystem in one vehicle. Less volatile than single names.',
  },
  {
    ticker: 'STM',
    name: 'STMicroelectronics NV',
    exchange: 'NYSE',
    securityType: 'EQUITY',
    quantity: 2.0,
    bookValueCAD: 108.81,
    bookValueMkt: 77.294,
    bookValueMktCurrency: 'USD',
    marketPrice: 44.49,
    marketPriceCurrency: 'USD',
    marketValue: 88.98,
    marketValueCurrency: 'USD',
    unrealizedReturn: 11.686,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'Semis',
    conviction: 5,
    horizon: 'MEDIUM',
    targetPct: 3,
    thesis: 'EV and industrial semi exposure. Underperforming on EV slowdown. Watching for recovery catalyst — may replace with broader semi exposure.',
  },
  {
    ticker: 'TTWO',
    name: 'Take-Two Interactive Software Inc.',
    exchange: 'NASDAQ',
    securityType: 'EQUITY',
    quantity: 1.539,
    bookValueCAD: 507.431,
    bookValueMkt: 360.897,
    bookValueMktCurrency: 'USD',
    marketPrice: 217.08,
    marketPriceCurrency: 'USD',
    marketValue: 334.086,
    marketValueCurrency: 'USD',
    unrealizedReturn: -26.811,
    unrealizedReturnCurrency: 'USD',
    bucket: 'Tactical',
    theme: 'Gaming',
    conviction: 6,
    horizon: 'MEDIUM',
    targetPct: 3,
    thesis: 'GTA VI catalyst expected to be largest entertainment launch ever. Significant unrealized loss — thesis dependent on GTA VI delivering in 2025.',
  },
  {
    ticker: 'VFV',
    name: 'Vanguard S&P 500 Index ETF',
    exchange: 'TSX',
    securityType: 'EXCHANGE_TRADED_FUND',
    quantity: 3.6495,
    bookValueCAD: 603.56,
    bookValueMkt: 603.56,
    bookValueMktCurrency: 'CAD',
    marketPrice: 171.5,
    marketPriceCurrency: 'CAD',
    marketValue: 625.889,
    marketValueCurrency: 'CAD',
    unrealizedReturn: 22.329,
    unrealizedReturnCurrency: 'CAD',
    bucket: 'Core',
    theme: 'Broad Market',
    conviction: 8,
    horizon: 'LONG',
    targetPct: 10,
    thesis: 'Broad market anchor in CAD. VFV hedges concentration in AI/semi themes. CAD-denominated removes FX risk. Strong long-run track record.',
  },
]

const watchlist = [
  { ticker: 'ARM', name: 'Arm Holdings', theme: 'Semi / AI', notes: 'Semi IP royalties, AI edge inference. Watching for pullback to $110–120.', alertPrice: 115 },
  { ticker: 'ASML', name: 'ASML Holding', theme: 'Semi Capex', notes: 'EUV monopoly, long-cycle semi capex. Entry at €650–700 range.', alertPrice: null },
  { ticker: 'VST', name: 'Vistra Energy', theme: 'Nuclear / Power', notes: 'Power/nuclear play for AI data center demand. Complements NLR.', alertPrice: null },
  { ticker: 'CEG', name: 'Constellation Energy', theme: 'Nuclear / Power', notes: 'Nuclear operator, Microsoft contract. AI power demand beneficiary.', alertPrice: null },
  { ticker: 'MSTR', name: 'MicroStrategy', theme: 'Crypto Proxy', notes: 'Bitcoin treasury proxy. Watching risk/leverage profile before sizing.', alertPrice: null },
]

const trends = [
  {
    name: 'AI / Data Center Cycle',
    signal: 'BULLISH',
    drivers: 'Hyperscaler capex at record highs|Inference demand scaling|Enterprise AI adoption accelerating',
    risks: 'Multiple compression risk|Export restrictions|Regulatory headwinds',
    tickers: 'NVDA,META,AVGO,PLTR,QQQM',
  },
  {
    name: 'Semiconductor Rally',
    signal: 'BULLISH',
    drivers: 'HBM3E demand from AI|CoWoS capacity expanding|TSMC pricing power increasing',
    risks: 'Cyclical inventory correction|US-China trade restrictions|Valuation at cycle highs',
    tickers: 'NVDA,AVGO,STM,SMHX',
  },
  {
    name: 'Nuclear Energy',
    signal: 'BULLISH',
    drivers: 'AI data center power demand|Policy tailwinds (IRA, nuclear permitting)|SMR technology maturing',
    risks: 'Construction delays|Capital costs|Public opposition',
    tickers: 'NLR',
  },
  {
    name: 'Commodities / Gold',
    signal: 'NEUTRAL',
    drivers: 'USD weakness|Central bank buying|Geopolitical uncertainty',
    risks: 'Rate hike reversal|USD strengthening|Demand slowdown',
    tickers: 'GDX,GOLD',
  },
  {
    name: 'Gaming',
    signal: 'NEUTRAL',
    drivers: 'GTA VI launch catalyst|Console cycle momentum|Mobile gaming growth',
    risks: 'GTA VI delay risk|Consumer spending sensitivity|High competition',
    tickers: 'TTWO',
  },
  {
    name: 'Valuation Concerns',
    signal: 'BEARISH',
    drivers: '',
    risks: 'AI semis at 40–90x revenue|Rate sensitivity at high multiples|Earnings miss risk at premium valuation',
    tickers: 'NVDA,PLTR,AVGO',
  },
]

const journalEntries = [
  {
    ticker: 'NVDA',
    title: 'NVDA — position review',
    body: 'NVDA continues to be the core holding. Blackwell ramp data impressive. H20 export restrictions create temporary headwind but thesis intact. Monitoring closely at current weight.',
    tags: 'review,core,AI',
    date: new Date('2026-04-18'),
  },
  {
    ticker: 'NLR',
    title: 'Nuclear thesis update',
    body: 'Data center power demand narrative accelerating. Microsoft, Google, Amazon all signing nuclear PPAs. NLR holding steady — considering adding on any dip. SMR timelines still 5+ years out but market is pricing in option value.',
    tags: 'nuclear,AI,power',
    date: new Date('2026-04-10'),
  },
  {
    ticker: 'STM',
    title: 'STM — conviction review',
    body: 'STM underperforming. EV slowdown dragging on industrial semi segment. Conviction at 5/10. Will reassess after next earnings — if guidance cut again, consider replacing with broader SOXX or SMHX exposure.',
    tags: 'review,semis,EV',
    date: new Date('2026-03-29'),
  },
  {
    ticker: 'PLTR',
    title: 'PLTR — valuation note',
    body: 'Palantir position small but profitable. Valuation stretched at current levels. Hold position, monitor AIP commercial growth rate. Do not add at these multiples — the thesis requires execution.',
    tags: 'review,AI,GovTech',
    date: new Date('2026-03-15'),
  },
  {
    ticker: 'TTWO',
    title: 'TTWO — thesis check',
    body: 'Position showing unrealized loss. Entire thesis rests on GTA VI. If launch slips again or underperforms, exit and redeploy into core positions. Watching closely.',
    tags: 'gaming,risk,thesis',
    date: new Date('2026-02-28'),
  },
]

async function main() {
  console.log('Seeding database with your real Wealthsimple holdings...')

  await prisma.holding.deleteMany()
  await prisma.watchlistItem.deleteMany()
  await prisma.macroTrend.deleteMany()
  await prisma.journalEntry.deleteMany()
  await prisma.portfolioSettings.deleteMany()

  for (const h of holdings) {
    await prisma.holding.create({ data: h })
    console.log(`  ✓ ${h.ticker} — ${h.name}`)
  }

  for (const w of watchlist) {
    await prisma.watchlistItem.create({ data: w })
  }

  for (const t of trends) {
    await prisma.macroTrend.create({ data: t })
  }

  for (const j of journalEntries) {
    await prisma.journalEntry.create({ data: j })
  }

  await prisma.portfolioSettings.create({
    data: {
      name: 'TFSA 2026',
      currency: 'CAD',
      tfsaRoom: 7200,
      maxPosition: 20,
      rebalanceTrigger: 5,
      alertsEnabled: true,
    },
  })

  console.log('\n✅ Database seeded successfully!')
  console.log(`   ${holdings.length} holdings | ${watchlist.length} watchlist items | ${trends.length} trends | ${journalEntries.length} journal entries`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
